@hostname = localhost
@port = 8080
@host = http://{{hostname}}:{{port}}


### 1. Registrar un nuevo usuario (ÉXITO - 201)
POST {{host}}/api/registro
Content-Type: application/json

{
  "username": "test4user",
  "password": "password",
  "email": "test4user@example.com"
}

### 2. Intentar registrar el mismo usuario (Error)
POST {{host}}/api/registro
Content-Type: application/json

{
  "username": "test5user",
  "password": "password",
  "email": "testuser@example.com"
}



### 3. Obtener todos los estudiantes (Verificar registro)
GET {{host}}/api/estudiantes
