@hostname = localhost
@port = 8080
@host = http://{{hostname}}:{{port}}


### 1. Registrar un nuevo estudiante con datos por defecto (ÉXITO - 201)
POST {{host}}/api/estudiantes/registro
Content-Type: application/json

{
  "username": "test8user",
  "password": "password",
  "email": "test8user@example.com"
}

### 2. Intentar registrar el mismo usuario (Error)
POST {{host}}/api/estudiantes/registro
Content-Type: application/json

{
  "username": "test6user",
  "password": "password",
  "email": "test6user@example.com"
}



### 3. Obtener todos los estudiantes (Verificar registro)
GET {{host}}/api/estudiantes



### 4. Login (funcionando con credenciales correctas e incorrectas)
POST {{host}}/api/login
Content-Type: application/json

{
  "identifier": "test6user",
  "password": "password"
}

### 5. Perfil del estudiante registrado (ÉXITO - 200)
GET {{host}}/api/estudiantes/perfil/diego

### 6. Editar el perfil del estudiante (ÉXITO - 200)
PUT {{host}}/api/estudiantes/perfil/test8user
Content-Type: application/json

{
  "nombre": "Test User 8",
  "apellido": "Apellido 8",
  "universidad": "Universidad Catolica Boliviana San Pablo",
  "carrera": "Ingenieria de Sistemas",
  "carnetIdentidad": "CI-8888888",
  "fechaNacimiento": "1998-08-08",
  "email": "test8user@example.com",
  "username": "test8user"
}